# Образ Python
FROM python:3.12-slim

# Рабочая директория внутри контейнера
WORKDIR /app

# Настройка PYTHONPATH
ENV PYTHONPATH=/app

# Копирование зависимостей
COPY ./requirements.txt /app

# Установка системных зависимостей
RUN apt-get update && \
    apt-get install -y \
        build-essential \
        libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Исправление проблемы
RUN sed -i 's/psycopg2==/psycopg2-binary==/g' requirements.txt

# Установка зависимостей
RUN pip install --no-cache-dir -r requirements.txt

# Копирование проекта в контейнер
COPY ./backend /app/backend
COPY ./web /app/web

# Открытие порта
EXPOSE 8000

